class SongBookAssets {
  static List songList = [
    {
      'Title': 'All Songs',
      'Location': 'Global',
      'Songs': '9768',
      'FileName': 'All',
      'DateAdded': '2026-02-02',
      'DateUpdated': '2026-02-02',
      'Languages': [
        'Afrikaans',
        'Bemba',
        'Changana',
        'English',
        'French',
        'German',
        'Kalenjin',
        'Lingala',
        'Ndebele',
        'Nyanja',
        'Português',
        'Shona',
        'Swahili',
        'Tagalog',
        'Tswana',
        'Xitchewa',
        'Zulu',
      ]
    },
    {
      'Title': 'Bible Tabernacle',
      'Location': 'Cape Town, South Africa',
      'FileName': 'BibleTabernacle_CapeTown_SA',
      'DateAdded': '2023-01-15',
      'DateUpdated': '2023-01-15',
      'Languages': ['Afrikaans', 'English']
    },
    {
      'Title': 'Cânticos Portugueses',
      'Location': 'Brazil',
      'FileName': 'CanticosPortugueses_Brasil',
      'DateAdded': '2026-06-05',
      'DateUpdated': '2026-06-27',
      'Languages': ['Português'],
    },
    {
      'Title': 'Chesilyot Word of Life Tabernacle',
      'Location': 'Bomet County, Kenya',
      'FileName': 'ChesilyotWordOfLifeTabernacle_BometCounty_Kenya',
      'DateAdded': '2025-06-19',
      'DateUpdated': '2025-06-19',
      'Languages': ['Kalenjin']
    },
    {
      'Title': 'City Tabernacle Bulawayo',
      'Location': 'Bulawayo, Zimbabwe',
      'FileName': 'CityTabernacleBulawayo_Bulawayo_Zimbabwe',
      'DateAdded': '2024-07-20',
      'DateUpdated': '2024-07-20',
      'Languages': ['English, Ndebele, Shona'],
    },
    {
      'Title': 'Christengemeinschaft in Westertimke',
      'Location': 'Westertimke, Germany',
      'FileName': 'WestertimkeTabernacle_Westertimke_Germany',
      'DateAdded': '2026-02-01',
      'DateUpdated': '2026-02-01',
      'Languages': ['English', 'German'],
    },
    {
      'Title': 'Eastlea Tabernacle',
      'Location': 'Harare, Zimbabwe',
      'FileName': 'EastleaTabernacle_Harare_Zimbabwe',
      'DateAdded': '2024-04-27',
      'DateUpdated': '2024-04-27',
      'Languages': [
        'English',
        'Ndebele',
        'Shona',
      ]
    },
    {
      'Title': 'Emmanuel Gospel Centre',
      'Location': 'Johannesburg, South Africa',
      'FileName': 'EmmanuelGospelCentre_Joburg_SA',
      'DateAdded': '2022-09-01',
      'DateUpdated': '2022-09-01',
      'Languages': ['English'],
    },
    {
      'Title': 'Harare Christian Fellowship',
      'Location': 'Harare, Zimbabwe',
      'FileName': 'HarareChristianFellowship_Harare_Zimbabwe',
      'DateAdded': '2022-08-01',
      'DateUpdated': '2022-08-01',
      'Languages': ['English', 'Ndebele', 'Shona'],
    },
    {
      'Title': 'Hebron Tabernacle',
      'Location': 'Lusaka, Zambia',
      'FileName': 'HebronTabernacle_Lusaka_Zambia',
      'DateAdded': '2023-10-17',
      'DateUpdated': '2023-10-17',
      'Languages': ['Bemba', 'English', 'Nyanja'],
    },
    {
      'Title': 'Kenya Local Believers',
      'Location': 'Nairobi, Kenya',
      'FileName': 'KenyaLocalBelievers_Nairobi_Kenya',
      'DateAdded': '2022-08-01',
      'DateUpdated': '2022-08-01',
      'Languages': ['English', 'Swahili'],
    },
    {
      'Title': 'Kilsyth Believers Christian Fellowship',
      'Location': 'Kilsyth, Scotland',
      'FileName': 'KilsythBelieversChristianFellowship_Kilsyth_Scotland',
      'DateAdded': '2023-01-15',
      'DateUpdated': '2023-01-15',
      'Languages': ['English', 'German']
    },
    {
      'Title': 'Nyimbo za Injili',
      'Location': 'Nairobi, Kenya',
      'FileName': 'NyimboZaInjili_Nairobi_Kenya',
      'DateAdded': '2022-08-01',
      'DateUpdated': '2022-08-01',
      'Languages': ['Swahili'],
    },
    {
      'Title': 'Revealed Word Tabernacle',
      'Location': 'Bulawayo, Zimbabwe',
      'FileName': 'RevealedWordTabernacle_Bulawayo_Zimbabwe',
      'DateAdded': '2022-08-01',
      'DateUpdated': '2022-08-01',
      'Languages': ['English', 'Ndebele', 'Shona'],
    },
    {
      'Title': 'Shekinah Tabernacle',
      'Location': 'Kinshasa, Congo',
      'FileName': 'ShekinahTabernacle_Kinshasa_DRC',
      'DateAdded': '2022-08-01',
      'DateUpdated': '2022-08-01',
      'Languages': ['French', 'Lingala'],
    },
    {
      'Title': 'Spoken Word Christian Assembly',
      'Location': 'Quezon City, Philippines',
      'FileName': 'SpokenWordChristianAssembly_QuezonCity_Philippines',
      'DateAdded': '2026-02-01',
      'DateUpdated': '2026-02-01',
      'Languages': ['English', 'Tagalog'],
    },
    {
      'Title': 'Tabernáculo de Maputo Interdenominacional',
      'Location': 'Maputo, Moçambizue',
      'FileName': 'InterdenominationalTabernacleOfMaputo',
      'DateAdded': '2024-06-30',
      'DateUpdated': '2024-06-30',
      'Languages': ['Changana', 'Português', 'Shona', 'Xitchewa']
    },
    {
      'Title': 'Token Tabernacle',
      'Location': 'Soweto, South Africa',
      'FileName': 'TokenTabernacle_Soweto_SA',
      'DateAdded': '2022-08-01',
      'DateUpdated': '2022-08-01',
      'Languages': ['English', 'French', 'Shona', 'Tswana', 'Zulu'],
    },
    {
      'Title': 'Third Exodus Assembly',
      'Location': 'Longdenville, Trinidad and Tobago',
      'FileName': 'ThirdExodusAssembly_Trinidad',
      'DateAdded': '2022-08-01',
      'DateUpdated': '2022-08-01',
      'Languages': ['English'],
    }
  ];
}
