// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXEPkRbJ7VCkhTRryRQtmUXx5QMcKwP2U',
    appId: '1:767948267709:web:2e3379316645c6691397d4',
    messagingSenderId: '767948267709',
    projectId: 'believers-songbook-v2-11edb',
    authDomain: 'believers-songbook-v2-11edb.firebaseapp.com',
    storageBucket: 'believers-songbook-v2-11edb.firebasestorage.app',
    measurementId: 'G-16WV5KD35G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTEqbLV5vYtecTcBumW1cLWJOLkVFgMo0',
    appId: '1:767948267709:android:551925aa151976ca1397d4',
    messagingSenderId: '767948267709',
    projectId: 'believers-songbook-v2-11edb',
    storageBucket: 'believers-songbook-v2-11edb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7emVBZS1H_JJj8Jbj_QxQFnKA6_nHB5Q',
    appId: '1:767948267709:ios:6317911d280248991397d4',
    messagingSenderId: '767948267709',
    projectId: 'believers-songbook-v2-11edb',
    storageBucket: 'believers-songbook-v2-11edb.firebasestorage.app',
    androidClientId: '767948267709-lvteea6cnsjqvjdat7bs87qij5v0c8tk.apps.googleusercontent.com',
    iosClientId: '767948267709-32n90o0ur07bvfulif6vnc058k3coenl.apps.googleusercontent.com',
    iosBundleId: 'com.ngonimujuru.songbookForBelievers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7emVBZS1H_JJj8Jbj_QxQFnKA6_nHB5Q',
    appId: '1:767948267709:ios:6317911d280248991397d4',
    messagingSenderId: '767948267709',
    projectId: 'believers-songbook-v2-11edb',
    storageBucket: 'believers-songbook-v2-11edb.firebasestorage.app',
    androidClientId: '767948267709-lvteea6cnsjqvjdat7bs87qij5v0c8tk.apps.googleusercontent.com',
    iosClientId: '767948267709-32n90o0ur07bvfulif6vnc058k3coenl.apps.googleusercontent.com',
    iosBundleId: 'com.ngonimujuru.songbookForBelievers',
  );

}